spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:mysql://localhost:3306/education
    username: user
    password: pass
    driver:
      class: name:com.mysql.cj.jdbc.Driver # database connection driver
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      # only update tables when new fields are created
      ddl-auto: update

    # show sql queries in the console
    show-sql: true
    properties:
      hibernate:
        format_sql: true

hibernate:
  dialect: org.hibernate.dialect.HSQLDialect

VAR1: "CONTENIDO DE VALOR1"
My.VAR2: 100
VAR3:
